# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPMJ5WGuT6yWjj2SthLoQpSBu27QHF0Z
"""

# Task 1: Fetch Data from HackerNews API and save to JSON

import requests
import time
import json
import os
from datetime import datetime

# -----------------------------
# API URLs
# -----------------------------
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# -----------------------------
# Category keywords (case-insensitive)
# -----------------------------
categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

# -----------------------------
# Function: Assign category based on title
# -----------------------------
def assign_category(title):
    """
    This function checks if any keyword is present in the title.
    If found, it assigns the corresponding category.
    """
    title = title.lower()
    for category, keywords in categories.items():
        for keyword in keywords:
            if keyword in title:
                return category
    return None  # No match

# -----------------------------
# Fetch top story IDs
# -----------------------------
headers = {"User-Agent": "TrendPulse/1.0"}

response = requests.get(TOP_STORIES_URL, headers=headers)
story_ids = response.json()

# -----------------------------
# Initialize storage
# -----------------------------
stories = []
category_count = {cat: 0 for cat in categories}

# -----------------------------
# Fetch each story details
# -----------------------------
for story_id in story_ids[:800]:   # Fetch more IDs to ensure enough valid stories

    try:
        res = requests.get(ITEM_URL.format(story_id), headers=headers)

        # Skip if request fails
        if res.status_code != 200:
            continue

        data = res.json()

        # Skip invalid entries
        if not data or "title" not in data:
            continue

        # Assign category
        category = assign_category(data["title"])

        # If no category match → assign "other"
        if not category:
            category = "other"

        # Limit only main categories (max 25 each)
        if category in category_count:
            if category_count[category] >= 25:
                continue
            category_count[category] += 1

        # Extract required fields
        story = {
            "post_id": data.get("id"),
            "title": data.get("title"),
            "category": category,
            "score": data.get("score", 0),
            "num_comments": data.get("descendants", 0),
            "author": data.get("by", "unknown"),
            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        # Add story to list
        stories.append(story)

        # Stop once we reach required count (>=125)
        if len(stories) >= 125:
            break

    except Exception as e:
        # If any error occurs, skip and continue
        continue

# -----------------------------
# Save data to JSON file
# -----------------------------
os.makedirs("data", exist_ok=True)

filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

with open(filename, "w") as f:
    json.dump(stories, f, indent=4)

# -----------------------------
# Final Output
# -----------------------------
print(f"Collected {len(stories)} stories. Saved to {filename}")