# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPMJ5WGuT6yWjj2SthLoQpSBu27QHF0Z
"""

# Task 3: Analyze cleaned data

import pandas as pd

# -----------------------------
# Step 1: Load cleaned CSV file
# -----------------------------
df = pd.read_csv("processed/cleaned_data.csv")

# -----------------------------
# Step 2: Basic dataset info
# -----------------------------
# Total number of stories collected
print("📊 Total Stories:", len(df))

# -----------------------------
# Step 3: Stories per category
# -----------------------------
# Helps understand distribution of categories
print("\n📌 Stories per Category:")
print(df['category'].value_counts())

# -----------------------------
# Step 4: Top 5 stories by score
# -----------------------------
# High score = more popular stories
print("\n🔥 Top 5 Stories by Score:")
top_score = df.sort_values(by='score', ascending=False).head(5)
print(top_score[['title', 'score']])

# -----------------------------
# Step 5: Most commented stories
# -----------------------------
# Shows engagement level
print("\n💬 Top 5 Most Commented Stories:")
top_comments = df.sort_values(by='num_comments', ascending=False).head(5)
print(top_comments[['title', 'num_comments']])

# -----------------------------
# Step 6: Average score per category
# -----------------------------
# Helps compare performance across categories
print("\n📈 Average Score per Category:")
print(df.groupby('category')['score'].mean())

# -----------------------------
# Step 7: Most active authors
# -----------------------------
# Authors with most posts
print("\n👤 Top 5 Authors:")
print(df['author'].value_counts().head(5))