# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPMJ5WGuT6yWjj2SthLoQpSBu27QHF0Z
"""

# Task 4: Visualize insights using matplotlib

import pandas as pd
import matplotlib.pyplot as plt

# -----------------------------
# Step 1: Load cleaned dataset
# -----------------------------
df = pd.read_csv("processed/cleaned_data.csv")

# -----------------------------
# Step 2: Bar Chart - Stories per Category
# -----------------------------
# This shows how stories are distributed across categories
category_counts = df['category'].value_counts()

plt.figure()
category_counts.plot(kind='bar')

plt.title("Stories per Category")
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# -----------------------------
# Step 3: Histogram - Score Distribution
# -----------------------------
# This shows how scores are spread across stories

plt.figure()
plt.hist(df['score'], bins=20)

plt.title("Score Distribution")
plt.xlabel("Score")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# -----------------------------
# Step 4: Scatter Plot - Score vs Comments
# -----------------------------
# This helps understand relationship between popularity and engagement

plt.figure()
plt.scatter(df['score'], df['num_comments'])

plt.title("Score vs Number of Comments")
plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.tight_layout()
plt.show()