# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPMJ5WGuT6yWjj2SthLoQpSBu27QHF0Z
"""

# Task 2: Clean JSON data and save as CSV

import pandas as pd
import json
import os

# -----------------------------
# Step 1: Load the latest JSON file
# -----------------------------

# List all files inside 'data' folder
files = os.listdir("data")

# Get the latest JSON file (sorted by name/date)
latest_file = sorted(files)[-1]

# Load JSON data
with open(f"data/{latest_file}", "r") as f:
    data = json.load(f)

# Convert JSON data into pandas DataFrame
df = pd.DataFrame(data)

# -----------------------------
# Step 2: Remove duplicate rows
# -----------------------------
# Duplicate records can affect analysis, so we remove them
df = df.drop_duplicates()

# -----------------------------
# Step 3: Handle missing values
# -----------------------------
# Instead of dropping rows, we fill missing values safely

df['score'] = df['score'].fillna(0)                 # Replace missing scores with 0
df['num_comments'] = df['num_comments'].fillna(0)   # Replace missing comments with 0
df['author'] = df['author'].fillna("unknown")       # Replace missing authors

# -----------------------------
# Step 4: Basic data cleaning
# -----------------------------
# Ensure correct data types

df['score'] = df['score'].astype(int)
df['num_comments'] = df['num_comments'].astype(int)

# -----------------------------
# Step 5: Save cleaned data to CSV
# -----------------------------
os.makedirs("processed", exist_ok=True)

output_path = "processed/cleaned_data.csv"

df.to_csv(output_path, index=False)

# -----------------------------
# Step 6: Print confirmation
# -----------------------------
print("✅ Cleaned data saved successfully!")
print("📁 File location:", output_path)
print("📊 Total records after cleaning:", len(df))